# Generated by Django 5.0.6 on 2024-05-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='horarios',
            field=models.TimeField(),
        ),
    ]
