# Generated by Django 5.0.6 on 2024-05-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_alter_show_horarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='imagem',
            field=models.ImageField(default=2, upload_to='shows/'),
            preserve_default=False,
        ),
    ]
